sonar.projectKey=spotify-recommender
sonar.projectName=Spotify Playlist Song Recommender
sonar.sourceEncoding=UTF-8
sonar.sources=frontend/src,backend/src,ml-service
sonar.tests=
sonar.exclusions=**/node_modules/**,**/venv/**,**/dist/**,**/.git/**
sonar.javascript.lcov.reportPaths=
