{
 "title": "Spotify DevOps Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Backend CPU",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"backend-health\"}[1m])"
    }
   ]
  },
  {
   "title": "ML CPU",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"ml-service-health\"}[1m])"
    }
   ]
  },
  {
   "title": "Backend Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(backend_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "ML Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(ml_service_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Backend Memory",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"backend-health\"}"
    }
   ]
  },
  {
   "title": "ML Memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"ml-service-health\"}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"spotify-recommender\"})"
    }
   ]
  }
 ]
}