global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend-health
    metrics_path: /health
    static_configs:
      - targets:
          - backend-service:3001

  - job_name: ml-service-health
    metrics_path: /health
    static_configs:
      - targets:
          - ml-service:5000

  - job_name: frontend-health
    metrics_path: /healthz
    static_configs:
      - targets:
          - frontend-service:80
